---
name: Checks

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY:
        description: "AWS access key"
        required: true

      AWS_SECRET_ACCESS_KEY:
        description: "AWS secret access key"
        required: true

      ENV_NAME:
        description: "Human redable name of the env"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Print Used env
        run: |
          echo "Env used is ${{ inputs.environment }}"
          echo "Human redable env is ${{ secrets.ENV_NAME }}"

