---
name: Checks

on:
  workflow_call: # This will trigger the workflow for any workflow call
  push: # No branches specified, so it will trigger on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: print content of README.md
        run: |
          echo "Printing content of README.md"
          cat README.md

      - name: Do the build
        run: echo "A build step" >> README.md

      - name: create zip
        run: zip openrail.zip README.md

      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: built_code
          path: openrail.zip