---
name: Checks

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY:
        description: "AWS access key"
        required: true

      AWS_SECRET_ACCESS_KEY:
        description: "AWS secret access key"
        required: true

      ENV_NAME:
        description: "Human redable name of the env"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      READABLE_ENV: ${{ secrets.ENV_NAME }}

    steps:
      - name: Print Used env
        run: |
          echo "Env used is ${{ inputs.environment }}"
          echo "Human readable env is ${READABLE_ENV:0:2}--${READABLE_ENV: -2}"
