name: Deploy
run-name: Release to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY:
        description: "AWS access key"
        required: true

      AWS_SECRET_ACCESS_KEY:
        description: "AWS secret access key"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: built_code
          path: artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: list contents
        run: ls -lR

      - name: Copy zip to s3
        run: aws s3 cp ./artifacts/built_code/openrail.zip s3://lambda-${{ inputs.environment }}/openrail/openrail.zip

#      - name: Zip code
#        run: |
#          zip openrail.zip target/build_artifact/README.md

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-west-1
#
#      - name: list env vars
#        run: env
##
