---
name: Deploy-UAT

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      environment: uat
    secrets: inherit

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: checks
    with:
      environment: uat
    secrets: inherit